# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f067c281066a7b76bad1fe511c64717806ee4788c6411d9fc56bba2c26084c9602674fd63ad53e97567a439b2d95c9124a6a987e6e8f179ee1131266fab4d293

test:
  secret_key_base: f6da57a4a71210d85a69416d731fe29f43718df9da2d46a46849cc0dc4becbf7439e2bbcd5bca67773bd85e630cadcf671792063812a52bfadc77f03d2d40828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
