# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71f27d1810b99ab0afd7a25fd42e2154d3d44e95b9f97dcb76e05ae6372def7c984893cbf42634f05be8b5bf57950f44b7e678aa0fdf26d515e445ec484cd17e

test:
  secret_key_base: 6855e0dc34a9b8d47733077ab02175be719d410f8fb49dc6bf8f2741df941f460a253bccbc109b402b58e4f6ffd31154f0ed2f874a4afe35b052d539105ebf73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
